name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@{scope}"
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: "🔍 run tests"
        run: pnpm run test

  lint:
    name: Code standarts
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@{scope}"
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: "🔍 lint code"
        run: pnpm run lint
