name: Development

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - develop
      - main

jobs:
  build:
    name: Lint, Tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@{scope}"
      - name: 📦 Install dependencies
        run: pnpm install

      - name: "📦 run build"
        run: pnpm run build

      - name: "🔍 lint code"
        run: pnpm run lint

      - name: "🔍 test code"
        run: pnpm run test
      
  deploy:
    if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/develop' }}
    name: Build container
    runs-on: ubuntu-latest
    needs: build
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Release"
