name: Development

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    name: Lint, Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, prettier, typescript]
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@{scope}"
      - name: 📦 Install dependencies
        run: pnpm install

      - name: "📦 run build"
        run: pnpm run build

      - name: "🔍 lint code"
        run: pnpm run lint
        
      - name: "🔍 test code"
        run: pnpm run test